echo -n "application " ; psql androidperformance -c "select count(*) from application" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "application_use " ; psql androidperformance -c "select count(*) from application_use" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "battery " ; psql androidperformance -c "select count(*) from battery" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "calculate_log " ; psql androidperformance -c "select count(*) from calculate_log" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "cell " ; psql androidperformance -c "select count(*) from cell" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "client_log " ; psql androidperformance -c "select count(*) from client_log" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "device " ; psql androidperformance -c "select count(*) from device" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "device_sim_join " ; psql androidperformance -c "select count(*) from device_sim_join" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "error_log " ; psql androidperformance -c "select count(*) from error_log" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "gps " ; psql androidperformance -c "select count(*) from gps" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "hop " ; psql androidperformance -c "select count(*) from hop" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "ipdv " ; psql androidperformance -c "select count(*) from ipdv" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "kill_list " ; psql androidperformance -c "select count(*) from kill_list" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "lastmile " ; psql androidperformance -c "select count(*) from lastmile" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "link " ; psql androidperformance -c "select count(*) from link" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "loss " ; psql androidperformance -c "select count(*) from loss" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "measurement " ; psql androidperformance -c "select count(*) from measurement" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "measurement_country_time " ; psql androidperformance -c "select count(*) from measurement_country_time" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "measurement_country_time_network " ; psql androidperformance -c "select count(*) from measurement_country_time_network" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "measurement_oct14dec14 " ; psql androidperformance -c "select count(*) from measurement_oct14dec14" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "network " ; psql androidperformance -c "select count(*) from network" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "ping " ; psql androidperformance -c "select count(*) from ping" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "ping_servers " ; psql androidperformance -c "select count(*) from ping_servers" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "screen " ; psql androidperformance -c "select count(*) from screen" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "sim " ; psql androidperformance -c "select count(*) from sim" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "south_migrationhistory " ; psql androidperformance -c "select count(*) from south_migrationhistory" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "state " ; psql androidperformance -c "select count(*) from state" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "throughput " ; psql androidperformance -c "select count(*) from throughput" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "traceroute " ; psql androidperformance -c "select count(*) from traceroute" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "usage " ; psql androidperformance -c "select count(*) from usage" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "values " ; psql androidperformance -c "select count(*) from values" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "warmup_experiment " ; psql androidperformance -c "select count(*) from warmup_experiment" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "warmup_ping " ; psql androidperformance -c "select count(*) from warmup_ping" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "wifi " ; psql androidperformance -c "select count(*) from wifi" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "wifi_hotspot " ; psql androidperformance -c "select count(*) from wifi_hotspot" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "wifi_neighbor " ; psql androidperformance -c "select count(*) from wifi_neighbor" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "za " ; psql androidperformance -c "select count(*) from za" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
echo -n "za1 " ; psql androidperformance -c "select count(*) from za1" | grep -v "\-\-\-" | grep -v count | grep -v row | sed -e "s/[[:space:]]\+//g" | head -n 1
