echo application >>/tmp/selectall.out; psql androidperformance -c "select * from application" >>/tmp/selectall.out
echo application_use >>/tmp/selectall.out; psql androidperformance -c "select * from application_use" >>/tmp/selectall.out
echo battery >>/tmp/selectall.out; psql androidperformance -c "select * from battery" >>/tmp/selectall.out
echo calculate_log >>/tmp/selectall.out; psql androidperformance -c "select * from calculate_log" >>/tmp/selectall.out
echo cell >>/tmp/selectall.out; psql androidperformance -c "select * from cell" >>/tmp/selectall.out
echo client_log >>/tmp/selectall.out; psql androidperformance -c "select * from client_log" >>/tmp/selectall.out
echo device >>/tmp/selectall.out; psql androidperformance -c "select * from device" >>/tmp/selectall.out
echo device_sim_join >>/tmp/selectall.out; psql androidperformance -c "select * from device_sim_join" >>/tmp/selectall.out
echo error_log >>/tmp/selectall.out; psql androidperformance -c "select * from error_log" >>/tmp/selectall.out
echo gps >>/tmp/selectall.out; psql androidperformance -c "select * from gps" >>/tmp/selectall.out
echo hop >>/tmp/selectall.out; psql androidperformance -c "select * from hop" >>/tmp/selectall.out
echo ipdv >>/tmp/selectall.out; psql androidperformance -c "select * from ipdv" >>/tmp/selectall.out
echo kill_list >>/tmp/selectall.out; psql androidperformance -c "select * from kill_list" >>/tmp/selectall.out
echo lastmile >>/tmp/selectall.out; psql androidperformance -c "select * from lastmile" >>/tmp/selectall.out
echo link >>/tmp/selectall.out; psql androidperformance -c "select * from link" >>/tmp/selectall.out
echo loss >>/tmp/selectall.out; psql androidperformance -c "select * from loss" >>/tmp/selectall.out
echo measurement >>/tmp/selectall.out; psql androidperformance -c "select * from measurement" >>/tmp/selectall.out
echo measurement_country_time >>/tmp/selectall.out; psql androidperformance -c "select * from measurement_country_time" >>/tmp/selectall.out
echo measurement_country_time_network >>/tmp/selectall.out; psql androidperformance -c "select * from measurement_country_time_network" >>/tmp/selectall.out
echo measurement_oct14dec14 >>/tmp/selectall.out; psql androidperformance -c "select * from measurement_oct14dec14" >>/tmp/selectall.out
echo network >>/tmp/selectall.out; psql androidperformance -c "select * from network" >>/tmp/selectall.out
echo ping >>/tmp/selectall.out; psql androidperformance -c "select * from ping" >>/tmp/selectall.out
echo ping_servers >>/tmp/selectall.out; psql androidperformance -c "select * from ping_servers" >>/tmp/selectall.out
echo screen >>/tmp/selectall.out; psql androidperformance -c "select * from screen" >>/tmp/selectall.out
echo sim >>/tmp/selectall.out; psql androidperformance -c "select * from sim" >>/tmp/selectall.out
echo south_migrationhistory >>/tmp/selectall.out; psql androidperformance -c "select * from south_migrationhistory" >>/tmp/selectall.out
echo state >>/tmp/selectall.out; psql androidperformance -c "select * from state" >>/tmp/selectall.out
echo throughput >>/tmp/selectall.out; psql androidperformance -c "select * from throughput" >>/tmp/selectall.out
echo traceroute >>/tmp/selectall.out; psql androidperformance -c "select * from traceroute" >>/tmp/selectall.out
echo usage >>/tmp/selectall.out; psql androidperformance -c "select * from usage" >>/tmp/selectall.out
echo values >>/tmp/selectall.out; psql androidperformance -c "select * from values" >>/tmp/selectall.out
echo warmup_experiment >>/tmp/selectall.out; psql androidperformance -c "select * from warmup_experiment" >>/tmp/selectall.out
echo warmup_ping >>/tmp/selectall.out; psql androidperformance -c "select * from warmup_ping" >>/tmp/selectall.out
echo wifi >>/tmp/selectall.out; psql androidperformance -c "select * from wifi" >>/tmp/selectall.out
echo wifi_hotspot >>/tmp/selectall.out; psql androidperformance -c "select * from wifi_hotspot" >>/tmp/selectall.out
echo wifi_neighbor >>/tmp/selectall.out; psql androidperformance -c "select * from wifi_neighbor" >>/tmp/selectall.out
echo za >>/tmp/selectall.out; psql androidperformance -c "select * from za" >>/tmp/selectall.out
echo za1 >>/tmp/selectall.out; psql androidperformance -c "select * from za1" >>/tmp/selectall.out
